
###

https://qyilcewitexjndalxkexol.online

###

POST https://qyilcewitexjndalxkexol.online/webhook_viber_channel/foo
Accept: application/json
Content-Type: application/json

{

}

###

POST https://qyilcewitexjndalxkexol.online/testing
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{

}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "query": "mutation { cloudMessagingPing }"
}

###

POST https://qyilcewitexjndalxkexol.online/auth/authenticate
Accept: application/json
Content-Type: application/json

{
    "idToken": "-"
}

###

http://80.240.25.97:5000

###

https://qyilcewitexjndalxkexol.online/auth/who
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "{ status }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "{ cacheRedisGetCacheByKey(cache_key: \"foo1\") }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { cacheRedisCommit(cache_key: \"foo1\", patch: { x1: 333 }) }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "{ collectionsDocsByTopic(topic: \"main\") }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { collectionsDocsUpsert(topic: \"main\", patches: [ { data: { id: \"68add2c9a461ac1b176fc84d\", data: { foo: 1 } } } ]) }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { collectionsDocsDrop(topic: \"main\", ids: [\"68add2c9a461ac1b176fc84d\"]) }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { viberChannelSetupSetWebhook(url: \"https://qyilcewitexjndalxkexol.online/webhook_viber_channel/foo1\", auth_token: \"55792a1839738787-c1944f4adcfe0153-b92072ba54fddfae\") }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { viberSendTextMessage(payload: { foo1: \"foo:bar:55555\" }) }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { viberChannelSetupChannelsDrop(channels: [\"foo1\"]) }"
}

###

POST https://qyilcewitexjndalxkexol.online/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
    "query": "mutation { viberSendPictureMessage(payload: { foo1: { text: \"pumpaj💯\", media: \"https://firebasestorage.googleapis.com/v0/b/ngapp---iec2cy5qtf---dev.firebasestorage.app/o/temp%2F2025-10-15%2001_24_23-temp_2025-02-23%2018_53_32-Window.png%20(320%C3%97252).jpg?alt=media&token=10222c8e-0d2b-424e-ab1b-390091d6133a\" } }) }"
}

###
